[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.35" }
color-eyre = "0.6.2"
lazy_static = "1.4.0"
rand = "0.8.5"
num-derive = "0.3"
num-traits = "0.2"